# Generated by Django 5.0.1 on 2024-03-20 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_teacher3_image_alter_book_id_alter_booking1_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking1',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.payment'),
        ),
    ]
