# Generated by Django 5.0.1 on 2024-03-20 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_booking1_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking1',
            name='payment',
        ),
    ]
