# Generated by Django 5.0.1 on 2024-03-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_payment_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
    ]
